export default {
  bodyhome: {
    flex: 6,
    alignItems: "center",
  },
  buttonshome: {
    flex: 2,
    flexDirection: "row",
  },
  container: {
    flex: 5,
  },
  header: {
    backgroundColor: "#03255F",
    height: 60,
  },
  icon: {
    color: "white",
  },
  imageContainer: {
    flex: 3,
  },
  body: {
    flex: 6,
    alignItems: "center",
  },
  buttons: {
    flex: 2,
    flexDirection: "row",
  },
  buttonBlue: {
    width: 110,
    height: 110,
    backgroundColor: "#03255F",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 3,
    marginLeft: 5,
  },
  buttonYellow: {
    width: 110,
    height: 110,
    backgroundColor: "#F5C300",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 5,
    marginLeft: 5,
  },
  textUsers: {
    fontSize: 17,
    color: "#F5C300",
    fontWeight: "bold",
    justifyContent: "center",
    textAlign: "center",
  },
  textCompany: {
    fontSize: 17,
    color: "#03255F",
    fontWeight: "bold",
    justifyContent: "center",
    textAlign: "center",
  },
  title: {
    flex: 1,
  },
  textTitle: {
    fontSize: 40,
    color: "#03255F",
    fontWeight: "bold",
    paddingTop: 30,
  },
  buttonPagar: {
    width: 200,
    height: 50,
    backgroundColor: "#F5C300",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 8,
    borderWidth: 1,
  },
  textPagar: {
    fontSize: 20,
    color: "#03255F",
    fontWeight: "bold",
  },
  buttonPlus: {
    width: 25,
    height: 25,
    backgroundColor: "#F5C300",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 8,
    borderWidth: 1,
  },
  buttonLess: {
    width: 25,
    height: 25,
    backgroundColor: "#F5C300",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 8,
    borderWidth: 1,
  },
  quantity: {
    flexDirection: "row",
  },
  form: {
    fontSize: 25,
    color: "#03255F",
    fontWeight: "bold",
    paddingTop: 30,
  },
  numero: {
    width: 25,
    height: 25,
    fontSize: 15,
    color: "#03255F",
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 8,
    borderWidth: 1,
  },
  input: {
    height: 40,
    borderBottomColor: "#ccc",
    borderBottomWidth: 1,
    width: 300,
  },
  buttonSubmit: {
    marginTop: 15,
    width: 350,
    height: 50,
    backgroundColor: "#F5C300",
    marginBottom: 10,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 3,
  },
  textSubmit: {
    fontSize: 20,
    color: "white",
    fontWeight: "bold",
  },
  buttons: {
    flex: 2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
  },
};
